In [1]:
import numpy as np

In [3]:
np

### Creating arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [14]:
sample_list = [1,2,3,4,5,7,12]
a = np.array(sample_list)

In [15]:
a[2] = 10

In [16]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [19]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-D arrays

In [22]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
n = np.array([
    [1,2,3],
    [4,5,6]
])

In [25]:
n[1,2]

np.int64(6)

In [26]:
n[1]

array([4, 5, 6])

In [28]:
n[:,1]

array([2, 5])

### Randomly generated arrays

In [33]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [35]:
np.random.seed(2)
100 *np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [34]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [37]:
np.random.randint(0,10,size=(5,2))

array([[4, 5],
       [7, 3],
       [6, 4],
       [3, 7],
       [6, 1]])

### Elementwise operations

In [39]:
a = np.arange(5)

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a + 10

array([10, 11, 12, 13, 14])

In [42]:
a * 2

array([0, 2, 4, 6, 8])

In [43]:
a > 2

array([False, False, False,  True,  True])

In [44]:
a[a>2]

array([3, 4])

### Summarizing operation

In [45]:
a.min()

np.int64(0)

In [46]:
a.max()

np.int64(4)

In [47]:
a.sum()

np.int64(10)

In [48]:
a.mean()

np.float64(2.0)

In [49]:
a.std()

np.float64(1.4142135623730951)

### Linear Algebra

In [51]:
a = np.array([2,4,5,6])

In [52]:
b = np.array([1,0,0,2])

In [53]:
a*b # element-wise operation

array([ 2,  0,  0, 12])

In [54]:
#vector*vector/vector*matrix/matrix*matrix
a.dot(b)

np.int64(14)

In [ ]:
#a.dot(b) = a@b

### Identidy matrix

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse matrix

In [59]:
a = np.random.randn(3,3)

In [60]:
a

array([[ 1.21046817, -0.02012954,  0.01039395],
       [-0.83283795, -0.11601058, -0.70162767],
       [-1.38939342,  0.49059556, -0.21943638]])

In [62]:
np.linalg.inv(a)

array([[ 8.68570241e-01,  1.60257007e-03,  3.60171188e-02],
       [ 1.86105011e+00, -5.90163174e-01,  1.97514409e+00],
       [-1.33871539e+00, -1.32957914e+00, -3.69332684e-01]])

### Pandas

In [63]:
import pandas as pd

In [66]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [68]:
df = pd.DataFrame(data = data, columns = columns)

In [69]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [70]:
df = pd.DataFrame(data)

In [71]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [72]:
df.head(2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

### Series

In [73]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [74]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [75]:
df[['Make','Model']]

      Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

In [76]:
df['id'] = [1,2,3,4,5]

In [77]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [79]:
del df['id']

KeyError: 'id'

In [80]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### Index

In [81]:
df.index

RangeIndex(start=0, stop=5, step=1)

### Accessing elements

In [83]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [84]:
df.loc[[1,2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [85]:
df.index = ['a','b','c','d','e']

In [86]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [87]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [92]:
df.iloc[1,2]

np.int64(2017)

In [94]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### Accessing elements

### Filtering

In [96]:
df[df['Year'] > 2010]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

### String Operations

In [97]:
df['Vehicle_Style']

a          sedan
b          Sedan
c    convertible
d        4dr SUV
e         Pickup
Name: Vehicle_Style, dtype: str

In [102]:
#df['Vehicle_Style']= df['Vehicle_Style'].str.lower().str.replace(' ','_')
df = df.assign(
    Vehicle_Style=df['Vehicle_Style'].str.lower().str.replace(' ', '_'))

In [103]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

### Summarising operations

In [104]:
df.MSRP.mean()

np.float64(30186.0)

In [105]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [108]:
df.Make.value_counts()

Make
Nissan     2
Hyundai    1
Lotus      1
GMC        1
Name: count, dtype: int64

In [111]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [113]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [114]:
df.isnull().sum().sum()

np.int64(1)